### ISSUE TITLE
[NVRTC_ERROR_COMPILATION] python3 scripts/train.py --gpus-sim

### ISSUE THREAD

**Issue by ZhuYQi** [shacklettbp/madrona_3d_example#12]
host envs
```
Operating System: Ubuntu 22.04.4 LTS
Kernel: Linux 6.5.0-18-generic
Architecture: x86-64
GPU: NVIDIA GeForce GTX 1660 
Driver Version: 560.35.03  
CUDA Version: 12.6
Docker version: 27.2.0, build 3ab4256
Nv Docker version: nvidia-docker2/unknown,now 2.13.0-1
```

how to reproduce it
```bash
# use image provided by nvidia
docker run -it --rm --gpus all -v $(readlink -f .):/root/ws nvidia/cuda:12.6.3-devel-ubuntu22.04
# install deps
apt update; apt install -y libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev mesa-common-dev python3-pip git python3-venv
pip install cmake==3.28
# build and install python module
cd /root/ws; rm -rf build/; mkdir -p build; cd build; cmake .. -DMADRONA_REQUIRE_CUDA=1; make -j; cd ..; pip install -e .
# exec training code
python3 scripts/train.py --num-worlds 8192 --num-updates 5000 --profile-report --fp16 --gpu-sim --ckpt-dir build/checkpoints/
```

error message:
```
root@1e32f5c1e00d:~/ws# python3 scripts/train.py --num-worlds 8192 --num-updates 5000 --profile-report --fp16 --gpu-sim --ckpt-dir build/checkpoints/
Compiling GPU engine code:
inlinable function call in a function with debug info must have a !dbg location
  call void @_ZN4cuda3std3__423__atomic_store_dispatchINS1_16__atomic_storageIiEEiNS1_25__thread_scope_device_tagELi0EEEvPT_T0_NS1_12memory_orderET1_(%struct._ZN4cuda3std3__416__atomic_storageIiEE* %15, i32 %16, i32 %17, %struct._ZN4cuda3std3__425__thread_scope_device_tagE %19)
inlinable function call in a function with debug info must have a !dbg location
  %15 = call i32 @_ZN4cuda3std3__422__atomic_load_dispatchINS1_16__atomic_storageIiEENS1_25__thread_scope_device_tagELi0EEENT_14__underlying_tEPKS6_NS1_12memory_orderET0_(%struct._ZN4cuda3std3__416__atomic_storageIiEE* %11, i32 %12, %struct._ZN4cuda3std3__425__thread_scope_device_tagE %14)
inlinable function call in a function with debug info must have a !dbg location
  %21 = call i32 @_ZN4cuda3std3__426__atomic_exchange_dispatchINS1_16__atomic_storageIiEEiNS1_25__thread_scope_device_tagELi0EEENT_14__underlying_tEPS6_T0_NS1_12memory_orderET1_(%struct._ZN4cuda3std3__416__atomic_storageIiEE* %16, i32 %17, i32 %18, %struct._ZN4cuda3std3__425__thread_scope_device_tagE %20)
inlinable function call in a function with debug info must have a !dbg location
  call void @_ZN4cuda3std3__423__atomic_store_dispatchINS1_16__atomic_storageIjEEjNS1_25__thread_scope_system_tagELi0EEEvPT_T0_NS1_12memory_orderET1_(%struct._ZN4cuda3std3__416__atomic_storageIjEE* %15, i32 %16, i32 %17, %struct._ZN4cuda3std3__425__thread_scope_system_tagE %19)
inlinable function call in a function with debug info must have a !dbg location
  %15 = call i32 @_ZN4cuda3std3__422__atomic_load_dispatchINS1_16__atomic_storageIjEENS1_25__thread_scope_system_tagELi0EEENT_14__underlying_tEPKS6_NS1_12memory_orderET0_(%struct._ZN4cuda3std3__416__atomic_storageIjEE* %11, i32 %12, %struct._ZN4cuda3std3__425__thread_scope_system_tagE %14)
inlinable function call in a function with debug info must have a !dbg location
  %21 = call i64 @_ZN4cuda3std3__427__atomic_fetch_add_dispatchINS1_16__atomic_storageIyEEyNS1_25__thread_scope_device_tagELi0EEENT_14__underlying_tEPS6_T0_NS1_12memory_orderET1_(%struct._ZN4cuda3std3__416__atomic_storageIyEE* %16, i64 %17, i32 %18, %struct._ZN4cuda3std3__425__thread_scope_device_tagE %20)
inlinable function call in a function with debug info must have a !dbg location
  call void @_ZN4cuda3std3__423__atomic_store_dispatchINS1_16__atomic_storageIiEEiNS1_25__thread_scope_device_tagELi0EEEvPT_T0_NS1_12memory_orderET1_(%struct._ZN4cuda3std3__416__atomic_storageIiEE* %6, i32 %4, i32 %5, %struct._ZN4cuda3std3__425__thread_scope_device_tagE zeroinitializer)
inlinable function call in a function with debug info must have a !dbg location
  %5 = call i32 @_ZN4cuda3std3__422__atomic_load_dispatchINS1_16__atomic_storageIiEENS1_25__thread_scope_device_tagELi0EEENT_14__underlying_tEPKS6_NS1_12memory_orderET0_(%struct._ZN4cuda3std3__416__atomic_storageIiEE* %4, i32 %3, %struct._ZN4cuda3std3__425__thread_scope_device_tagE zeroinitializer)
inlinable function call in a function with debug info must have a !dbg location
  %7 = call i32 @_ZN4cuda3std3__426__atomic_exchange_dispatchINS1_16__atomic_storageIiEEiNS1_25__thread_scope_device_tagELi0EEENT_14__underlying_tEPS6_T0_NS1_12memory_orderET1_(%struct._ZN4cuda3std3__416__atomic_storageIiEE* %6, i32 %4, i32 %5, %struct._ZN4cuda3std3__425__thread_scope_device_tagE zeroinitializer)
inlinable function call in a function with debug info must have a !dbg location
  call void @_ZN4cuda3std3__423__atomic_store_dispatchINS1_16__atomic_storageIjEEjNS1_25__thread_scope_system_tagELi0EEEvPT_T0_NS1_12memory_orderET1_(%struct._ZN4cuda3std3__416__atomic_storageIjEE* %6, i32 %4, i32 %5, %struct._ZN4cuda3std3__425__thread_scope_system_tagE zeroinitializer)
inlinable function call in a function with debug info must have a !dbg location
  %5 = call i32 @_ZN4cuda3std3__422__atomic_load_dispatchINS1_16__atomic_storageIjEENS1_25__thread_scope_system_tagELi0EEENT_14__underlying_tEPKS6_NS1_12memory_orderET0_(%struct._ZN4cuda3std3__416__atomic_storageIjEE* %4, i32 %3, %struct._ZN4cuda3std3__425__thread_scope_system_tagE zeroinitializer)
inlinable function call in a function with debug info must have a !dbg location
  %7 = call i64 @_ZN4cuda3std3__427__atomic_fetch_add_dispatchINS1_16__atomic_storageIyEEyNS1_25__thread_scope_device_tagELi0EEENT_14__underlying_tEPS6_T0_NS1_12memory_orderET1_(%struct._ZN4cuda3std3__416__atomic_storageIyEE* %6, i64 %4, i32 %5, %struct._ZN4cuda3std3__425__thread_scope_device_tagE zeroinitializer)
error: Broken module found, compilation aborted!


Error at /root/ws/external/madrona/src/mw/cpp_compile.cpp:81 in auto madrona::cu::jitCompileCPPSrc(const char *, const char *, const char **, uint32_t, const char **, uint32_t, bool)::(anonymous class)::operator()() const
NVRTC_ERROR_COMPILATION
```

**Comment by ZhuYQi** [comment]
the error above is triggered when
scripts/train.py
```python
import madrona_escape_room
import torch
```

the original code
```python
import torch
import madrona_escape_room
```
will raise error like:
```
root@1e32f5c1e00d:~/ws# python3 scripts/train.py --num-worlds 8192 --num-updates 5000 --profile-report --fp16 --gpu-sim --ckpt-dir build/checkpoints/
Traceback (most recent call last):
  File "/root/ws/scripts/train.py", line 2, in <module>
    import madrona_escape_room
ImportError: /root/ws/build/madrona_escape_room.cpython-310-x86_64-linux-gnu.so: undefined symbol: __nvJitLinkCreate_12_6, version libnvJitLink.so.12
```

**Comment by shacklettbp** [comment]
Due to an nvidia bug, CUDA 12.6 does not work. You need to upgrade to CUDA 12.8

**Comment by ZhuYQi** [comment]
CUDA 12.8 still no work，i've tried with nvidia/cuda:12.8.1-devel-ubuntu22.04

```
/root/ws/external/madrona/src/common/../../include/madrona/sync.hpp(334): error: qualified name is not allowed
      cuda::atomic_ref<T, cuda::thread_scope_device> ref_;
      ^
```
```
/root/ws/external/madrona/src/common/../../include/madrona/sync.hpp(183): error: qualified name is not allowed
      cuda::atomic<T, cuda::thread_scope_device> impl_;
      ^
```

GPT says "This indicates that in CUDA 12.8, the atomic template no longer accepts two parameters (type and scope) as direct template arguments."

Could you provide the tested driver/CUDA version combinations for the current default branch? This would help ensure compatibility in our environment.

**Comment by ZhuYQi** [comment]
Does Madrona have plans to release containerized (Docker) builds in the future?  this would be extremely helpful.

**Comment by shacklettbp** [comment]
My mistake, I forgot this environment hadn't been updated in awhile and was using an out of date Madrona. If you pull the latest commit on this branch and git submodule update --init --recursive, it should work with CUDA 12.8 now.

**Comment by shacklettbp** [comment]
No plans to release docker containers, happy to accept PRs.

**Comment by ZhuYQi** [comment]
> My mistake, I forgot this environment hadn't been updated in awhile and was using an out of date Madrona. If you pull the latest commit on this branch and git submodule update --init --recursive, it should work with CUDA 12.8 now.

it works on the latest madrona, thx!
